### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by winston0410** [soundslikeyin/html-from-form-exercise#1]
Use `h2` instead of `h3` (I guess you are doing this for styling reason)

https://github.com/soundslikeyin/html-from-form-exercise/blob/de60024e4001d05e1ab35bd3b933c0f5cbd6e716/index.html#L51

`method` only accepts `GET` and `POST`

https://github.com/soundslikeyin/html-from-form-exercise/blob/de60024e4001d05e1ab35bd3b933c0f5cbd6e716/index.html#L14

You dont need to use `for` here, enclosing the `<input>` as children is enough

https://github.com/soundslikeyin/html-from-form-exercise/blob/de60024e4001d05e1ab35bd3b933c0f5cbd6e716/index.html#L51

should be `text`

https://github.com/soundslikeyin/html-from-form-exercise/blob/de60024e4001d05e1ab35bd3b933c0f5cbd6e716/index.html#L76

**Comment by soundslikeyin** [comment]
Made the changes for each of these comment. Thank you!

> Use `h2` instead of `h3` (I guess you are doing this for styling reason)
> 
> https://github.com/soundslikeyin/html-from-form-exercise/blob/de60024e4001d05e1ab35bd3b933c0f5cbd6e716/index.html#L51
> 
> `method` only accepts `GET` and `POST`
> 
> https://github.com/soundslikeyin/html-from-form-exercise/blob/de60024e4001d05e1ab35bd3b933c0f5cbd6e716/index.html#L14
> 
> You dont need to use `for` here, enclosing the `<input>` as children is enough
> 
> https://github.com/soundslikeyin/html-from-form-exercise/blob/de60024e4001d05e1ab35bd3b933c0f5cbd6e716/index.html#L51
> 
> should be `text`
> 
> https://github.com/soundslikeyin/html-from-form-exercise/blob/de60024e4001d05e1ab35bd3b933c0f5cbd6e716/index.html#L76
